version: '3.8'

services:
  api:
    build: .
    container_name: ai-interview-api
    command: api
    env_file:
      - .env
    ports:
      - "80:10000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
