"""Add examples column

Revision ID: c7f12a3e98b0
Revises: dedc4ecff85c
Create Date: 2026-04-19 16:21:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c7f12a3e98b0'
down_revision: Union[str, Sequence[str], None] = 'dedc4ecff85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('examples', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'examples')
    # ### end Alembic commands ###
