"""Add coding interview support

Revision ID: dedc4ecff85c
Revises: 966df17a95a1
Create Date: 2026-04-18 17:33:49.152923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dedc4ecff85c'
down_revision: Union[str, Sequence[str], None] = '966df17a95a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('code', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('interview_type', sa.String(length=50), server_default='behavioral', nullable=False))
    op.add_column('questions', sa.Column('question_type', sa.String(length=50), server_default='behavioral', nullable=False))
    op.add_column('questions', sa.Column('starter_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'starter_code')
    op.drop_column('questions', 'question_type')
    op.drop_column('interviews', 'interview_type')
    op.drop_column('answers', 'language')
    op.drop_column('answers', 'code')
    # ### end Alembic commands ###
